PRE_COMMANDS:
- command: pip install pytest ament-lint-pep257 ament-lint-flake8
  venv: pylint
- command: pip install pytest ament-lint-pep257 ament-lint-flake8
  venv: black
- command: pip install pytest ament-lint-pep257 ament-lint-flake8
  venv: flake8
- command: pip install pytest ament-lint-pep257 ament-lint-flake8
  venv: isort
- command: pip install pytest ament-lint-pep257 ament-lint-flake8
  venv: bandit
- command: pip install pytest ament-lint-pep257 ament-lint-flake8
  venv: mypy
- command: pip install pytest ament-lint-pep257 ament-lint-flake8
  venv: pyright
- command: pip install pytest ament-lint-pep257 ament-lint-flake8
  venv: ruff

DISABLE:
  - COPYPASTE

DISABLE_LINTER:
  - PYTHON_PYLINT