PRE_COMMANDS:
# - command: pip install pytest ament-lint-pep257 ament-lint-flake8 flake8==4.0.1
#   venv: pylint
- command: pip install pytest ament-lint-pep257 ament-lint-flake8 flake8==4.0.1 pyqt6
  venv: black
- command: pip install pytest ament-lint-pep257 ament-lint-flake8 flake8==4.0.1 pyqt6
  venv: flake8
- command: pip install pytest ament-lint-pep257 ament-lint-flake8 flake8==4.0.1 pyqt6
  venv: isort
- command: pip install pytest ament-lint-pep257 ament-lint-flake8 flake8==4.0.1 pyqt6
  venv: bandit
- command: pip install pytest ament-lint-pep257 ament-lint-flake8 flake8==4.0.1 pyqt6
  venv: mypy
# - command: pip install pytest ament-lint-pep257 ament-lint-flake8 flake8==4.0.1
#   venv: pyright
- command: pip install pytest ament-lint-pep257 ament-lint-flake8 flake8==4.0.1 pyqt6
  venv: ruff

DISABLE:
  - COPYPASTE

DISABLE_LINTERS:
  - PYTHON_PYLINT
  # MYPY is doing enough type checking
  - PYTHON_PYRIGHT