---
# Hadolint config files funky right now.
DOCKERFILE_HADOLINT_ARGUMENTS:
  --ignore SC1091


PYTHON_BLACK_CONFIG_FILE: pyproject.toml
PYTHON_RUFF_CONFIG_FILE: pyproject.toml
PYTHON_ISORT_CONFIG_FILE: pyproject.toml
PYTHON_BANDIT_CONFIG_FILE: pyproject.toml
PYTHON_FLAKE8_CONFIG_FILE: pyproject.toml

DISABLE:
  - COPYPASTE


PRE_COMMANDS:
  - pip install .

DISABLE_LINTERS:
  - PYTHON_PYLINT
  # MYPY is doing enough type checking
  - PYTHON_PYRIGHT
  # MYPY cannot do a good job without install all python dependencies so will disable here and use in ROS linter.
  # - PYTHON_MYPY
  # Seems broken rn
  - JSON_JSONLINT
  # workaround to solve the issue: fatal: detected dubious ownership in repository at '/github/workspace'
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS
