---
# Hadolint config files funky right now.
DOCKERFILE_HADOLINT_ARGUMENTS:
  --ignore SC1091

PYTHON_MYPY_CONFIG_FILE: pyproject.toml
PYTHON_BLACK_CONFIG_FILE: pyproject.toml
PYTHON_RUFF_CONFIG_FILE: pyproject.toml
PYTHON_ISORT_CONFIG_FILE: pyproject.toml
PYTHON_BANDIT_CONFIG_FILE: pyproject.toml

# DO this heheheha because of https://github.com/PyCQA/flake8/issues/234
# Where grown adults just complain and complain lol.
PRE_COMMANDS:
  - command: pip install --upgrade pip && pip install Flake8-pyproject
    venv: flake8
  - command: pip install --upgrade pip && pip install pytest ament_mypy ament_flake8
    venv: mypy
PYTHON_FLAKE8_ARGUMENTS: --toml-config /github/workspace/pyproject.toml

POST_COMMANDS:
  - command: ls
  - command: apt-get install qt6-base-dev

DISABLE:
  - COPYPASTE

DISABLE_LINTERS:
  - PYTHON_PYLINT
  # MYPY is doing enough type checking
  - PYTHON_PYRIGHT
  # MYPY cannot do a good job without install all python dependencies so will disable here and use in ROS linter.
  # - PYTHON_MYPY
  # Seems broken rn
  - JSON_JSONLINT
  # workaround to solve the issue: fatal: detected dubious ownership in repository at '/github/workspace'
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS
