FROM osrf/ros:iron-desktop-full

RUN sudo apt-get update -y

# Install pip
RUN sudo apt-get install python3-pip -y

# Install Video for Linux
RUN sudo apt-get install v4l-utils -y

# Install lsusb
RUN sudo apt-get install usbutils -y

# Install nano
RUN sudo apt-get install nano -y

RUN sudo apt-get update -y
RUN sudo apt-get upgrade -y

#Set up rov user
ARG USER_NAME=rov
ARG USER_UID=1000
ARG USER_GID=1000

RUN groupadd ${USER_NAME} --gid ${USER_GID}\
    && useradd -l -m ${USER_NAME} -u ${USER_UID} -g ${USER_GID} -s /bin/bash

# Gives Sudo perms to USER
RUN echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USER_NAME}
RUN chmod 0440 /etc/sudoers.d/${USER_NAME}

# Adds $USER to environment
ENV USER ${USER_NAME}
# Switches to rov user
USER ${USER_NAME}

WORKDIR /home/${USER_NAME}

# Setup Ardusub
COPY src/surface/rov_gazebo/scripts/ardusub.sh .
RUN ./ardusub.sh \
 && rm ardusub.sh

# Setup Ardupilot Gazebo
COPY src/surface/rov_gazebo/scripts/ardupilot_gazebo.sh .
RUN ./ardupilot_gazebo.sh \
    && rm ardupilot_gazebo.sh

# Remove identity file generated by action/checkout
# Start by finding all files ending in config
# Then removes file paths without "git"
# Then removes the 'sshCommand' line from each file
RUN  find . -name "*config" | grep git | while read -r line; do sed -i '/sshCommand/d' $line; done

# Install geographiclib dependencies for mavros.
RUN sudo su -c "bash <(wget -qO- https://raw.githubusercontent.com/mavlink/mavros/ros2/mavros/scripts/install_geographiclib_datasets.sh)" root

WORKDIR /home/${USER_NAME}/rov-24

# Remove build warnings
ENV PYTHONWARNINGS ignore:::setuptools.command.install,ignore:::setuptools.command.easy_install,ignore:::pkg_resources

COPY . .

# TODO for future nerd to do this via ENTRYPOINT which be better but, I could not get ENTRYPOINT to play with VsCODE.
RUN ./.vscode/rov_setup.sh

# Installs ROS and python dependencies
RUN ./.vscode/install_dependencies.sh

RUN . /opt/ros/iron/setup.sh \
  && PYTHONWARNINGS=ignore:::setuptools.command.install,ignore:::setuptools.command.easy_install,ignore:::pkg_resources; export PYTHONWARNINGS \
  && colcon build --symlink-install

# Setup Models and Gazebo Environment
RUN ./src/surface/rov_gazebo/scripts/add_models_and_worlds.sh
