version: '3.9'
services:
  ros:
    image: ghcr.io/cwrurobotics/rov-24:docker
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ~/.ssh:/home/user/.ssh:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    stdin_open: true