FROM osrf/ros:iron-desktop-full

RUN apt-get update -y \
  && apt-get install --no-install-recommends -y \
  # Install Video for Linux
  v4l-utils=1.22.1-2build1 -y \
  # Install lsusb
  usbutils=1:014-1build1 \
  # Install nano
  nano=6.2-1 \
  # Install pip
  python3-pip=22.0.2+dfsg-1ubuntu0.4\
  && apt-get upgrade -y \
  # Clean for better performance
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

#Set up rov user
ARG USER_NAME=rov
ARG USER_UID=1000
ARG USER_GID=1000

RUN groupadd ${USER_NAME} --gid ${USER_GID} \
    && useradd -l -m ${USER_NAME} -u ${USER_UID} -g ${USER_GID} -s /bin/bash

# Gives Sudo perms to USER
RUN echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USER_NAME} \
  && chmod 0440 /etc/sudoers.d/${USER_NAME}

# Adds $USER to environment
ENV USER ${USER_NAME}
# Switches to rov user
USER ${USER_NAME}

# Update Pip
RUN pip install --no-cache-dir --upgrade  pip==24.0 

WORKDIR /home/${USER_NAME}/rov-24

# One might wonder why the following is done.
# It is done so that the dependencies can be cached without needing to be reinstalled
# each and everytime. Since these do not change too often this improves performance in most cases

# Copies in Python deps
COPY pyproject.toml .
# Copies in ROS deps
RUN mkdir src
COPY package.xml* ./src
# Copies in Install Script
COPY .vscode/install_dependencies.sh .

# Installs ROS and python dependencies
RUN ./install_dependencies.sh \
  # Clean up
  && rm -r src \
  && rm install_dependencies.sh


# Remove build warnings
ENV PYTHONWARNINGS ignore:::setuptools.command.install,ignore:::setuptools.command.easy_install,ignore:::pkg_resources

# TODO for future nerd to do this via ENTRYPOINT which be better but, I could not get ENTRYPOINT to play with VsCODE.
COPY .vscode/rov_setup.sh .
RUN ./rov_setup.sh \
  && rm rov_setup.sh

COPY .git .git
# Remove identity file generated by action/checkout
# Start by finding all files ending in config
# Then removes file paths without "git"
# Then removes the 'sshCommand' line from each file
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
USER root
RUN  find . -name "*config" | grep git | while read -r line; do sed -i "/sshCommand/d" "$line"; done
USER ${USER_NAME}

# Do full copy and build as last step
COPY . .
RUN . /opt/ros/iron/setup.sh \
    && PYTHONWARNINGS=ignore:::setuptools.command.install,ignore:::setuptools.command.easy_install,ignore:::pkg_resources; export PYTHONWARNINGS\
    && colcon build --symlink-install
