model_name: "bluerov2_heavy"
mass: 13.0
control_method: 0
bounding_box:
  x: 0.457
  y: 0.575
  z: 0.254
center_of_mass:
  x: 0.0
  y: 0.0
  z: 0.011
center_of_volume:
  x: 0.0
  y: 0.0
  z: 0.06
buoyancy_adjustment: 0.1
inertia:
  ixx: 0.26
  iyy: 0.23
  izz: 0.37
thrusters:
  - x: 0.14 # Thruster 1
    y: -0.092
    z: 0.0
  - x: 0.14 # Thruster 2
    y: 0.092
    z: 0.0
  - x: -0.15 # Thruster 3
    y: -0.092
    z: 0.0
  - x: -0.15 # Thruster 4
    y: 0.092
    z: 0.0
  - x: 0.118 # Thruster 5
    y: -0.215
    z: 0.064
  - x: 0.118 # Thruster 6
    y: 0.215
    z: 0.064
  - x: -0.118 # Thruster 7
    y: -0.215
    z: 0.064
  - x: -0.118 # Thruster 8
    y: 0.215
    z: 0.064